apiVersion: apps/v1
kind: Deployment
metadata:
  name: iron-gallery
  labels:
    app: iron-gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iron-gallery
  template:
    metadata:
      labels:
        app: iron-gallery
        run: iron-gallery
    spec:
      volumes:
        - name: config
          emptyDir:
        - name: images
          emptyDir:
      containers:
      - name: iron-gallery
        image: kodekloud/irongallery:2.0
        volumeMounts:
          - name: config
            mountPath: '/usr/share/nginx/html/data'
          - name: images
            mountPath: '/usr/share/nginx/html/uploads'
        resources:
          limits:
            memory: '100Mi'
            cpu: '50m'
