apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      volumes:
      - name: drupal-pvc
        persistentVolumeClaim:
          claimName: drupal-pvc
      containers:
      - name: drupal
        image: drupal:8.6
        volumeMounts:
        - mountPath: "/var/www/html/modules"
          subPath: modules
          name: drupal-pvc
        - mountPath: "/var/www/html/profiles"
          subPath: profiles
          name: drupal-pvc
        - mountPath: "/var/www/html/sites"
          subPath: sites
          name: drupal-pvc
        - mountPath: "/var/www/html/themes"
          subPath: themes
          name: drupal-pvc
      initContainers:
      - name: init-sites-volume
        image: drupal:8.6
        command: ["/bin/bash", "-c"]
        args: ['cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
        volumeMounts:
        - mountPath: "/data"
          name: drupal-pvc
