apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  selector:
    app: drupal
  ports:
    - protocol: TCP
      port: 30095
      targetPort: 30095
      nodePort: 30095
  type: NodePort
