apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  namespace: development
  labels:
    run: jekyll
spec:
  volumes:
    - name: site
      persistentVolumeClaim:
        claimName: jekyll-site
  containers:
    - name: jekyll
      image: kodekloud/jekyll-serve
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/site"
          name: site
  initContainers:
  - name: copy-jekyll-site
    image: kodekloud/jekyll
    command: ["jekyll", "new", "/site"]
    volumeMounts:
    - name: site
      mountPath: "/site"
